spring:
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  application:
    name: server
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL:
          DEBUG

server:
  port: 8888
  address: 0.0.0.0

springdoc:
  swagger-ui:
    urls:
      - name: contract
        url: /openapi-contract.yaml
#      - name: implementation
#        url: /v3/api-docs


jwt:
  secret: "randomsecretrandomsecretrandomsecretrandomsecretrandomsecretrandomsecret"