spring:
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  application:
    name: server
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL:
          DEBUG

server:
  port: 8888
  address: 0.0.0.0

#springdoc:
#  api-docs:
#    enabled: false
#  swagger-ui:
#    url: /openapi.yaml
#    path: /swagger-ui.html


jwt:
  secret: "randomsecretrandomsecretrandomsecretrandomsecretrandomsecretrandomsecret"